name: Art by Cesar
favicon: null
layout_spectrum: 0.74378
typography_spectrum: 0.30022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090909'
    - '#7b7f82'
    - '#494a4c'
    - '#2994ca'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
