layout_spectrum: 0.4537910029757768
typography_spectrum: 0.7974498148541898
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9603731464594603
  lightness: 0.7432160007301718
  saturation: 0.33761554257944226
  rhythmicContrast: 0.14523977087810636
name: Art by Cesar
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
